name: DevSecOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-secure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✅ Lint
      - name: Run Linter (flake8)
        run: flake8 .

      # ✅ Tests
      - name: Run Unit Tests
        run: pytest --maxfail=1 --disable-warnings -q

      # ✅ Static Security Scan
      - name: Bandit Scan (Python Security)
        run: bandit -r .

      # ✅ CodeQL (for deeper analysis)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
